name: bandito

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      working-directory: .
      run: |
        make requirements_test
    - name: Run linting
      working-directory: .
      run: make lint

    - name: Run tests
      working-directory: .
      run: make test

    - name: Run typechecking
      working-directory: .
      run: make typecheck
